# RBS Targets
[RBS_TARGETS]
name = Target_RBS_1234
azimuth_deg = 60.0
range_km = 100.0
rbs_code_octal = 01234
spi = false
enabled = true
update_every_n_revolutions = 1
revolution_offset = 0
altitude_meters = 9600
enable_altitude = true
alternate_code_altitude = true

# Параметры линейного движения
use_linear_motion = true
speed_m_per_s = 200.0
course_deg = 260.0
initial_x_km = 86.6    # 100*sin(60°)
initial_y_km = 50.0    # 100*cos(60°)
end
